### ISSUE TITLE
Publish `knx.js` 0.7.5

### ISSUE THREAD

**Issue by nioc** [estbeetoo/knx.js#10]
Hello @aborovsky @ykornilov @pkess @s0meone.

Could you please publish `knx.js` 0.7.5 to npm?
It should resolve estbeetoo/node-red-contrib-knx#31.

Thanks for your work.

**Comment by pkess** [comment]
I am sorry, but i do not have any idea how to publish this. But i would like to get this released too

**Comment by nioc** [comment]
We need a npm maintainer (_someone who is allowed to publish releases on https://www.npmjs.com/package/knx.js_).
@aborovsky could you add someone of your choice (maybe an already known contributor) as a maintainer?

![image](https://user-images.githubusercontent.com/5225411/151899506-01cad752-dfaf-43bc-9411-f2948737b8ba.png)


Then, it is just about ([npm doc](https://docs.npmjs.com/cli/v8/commands/npm-publish)):
``` 
npm login
npm publish --tag 0.7.5
```

**Comment by aborovsky** [comment]
@nioc Sorry for late response, but i did! 0.7.5 released. Thx for your interest to current library.
![image](https://user-images.githubusercontent.com/1669420/152105375-e68e4576-5476-41d3-8b68-f7396aff3f1e.png)

**Comment by nioc** [comment]
@aborovsky Thanks a lot! I'll update my node-red tonight 😄
Probably this one estbeetoo/node-red-contrib-knx#31 should be closed too.
