### ISSUE TITLE
Error when multiple commands executed in small time frame

### ISSUE THREAD

**Issue by mishoboss** [estbeetoo/knx.js#3]
Hi, I get this error when multiple commands executed in small time frame:

```
Error: Not running
at Socket._healthCheck (dgram.js:421:11)
at Socket.send (dgram.js:273:8)
at KnxSenderTunneling.SendData (knx.js/src/KnxSenderTunneling.js:43:21)
at KnxSenderTunneling.KnxSender.Action (knx.js/src/KnxSender.js:9:10)
at KnxConnectionTunneling.KnxConnection.Action (knx.js/src/KnxConnection.js:119:20)
```

BTW, is this project still alive? I would like to use it in long term for my home automation needs.

**Comment by aborovsky** [comment]
Hi, @mishoboss!
Thank you for reporting.
Yes, project is alive.
We are constantly using it as a part of current project: https://github.com/estbeetoo/node-red-contrib-knx.

Please, provide small test suite (just code sending KNX datagrams) to let us repeat current bug ourself.

**Comment by aborovsky** [comment]
Hi, @mishoboss.
Are you using current library in your long term home aitomation project?
Do you still experiencing problem while sending a bunch of multiple commands in small time?

**Comment by mishoboss** [comment]
Hi, Alex,
unfortunately I have literally no free time lately to develop my project, but the plan stays unchanged and I want to use knx.js in long term. If I remember right the above error shows when commands are sent very quickly one after another. If there is some millis interval between them, it is OK. Sorry for being not very descriptive and not giving an example. Time is really an issue lately :(

**Comment by aborovsky** [comment]
Don't blame yourself, it's ok :)
Yes, driver has a queue logic with proper intervals between commands: it
send each next command only after previous command's feedback/ack received.
Or timeout occured, if there was no response from KNX bus.
Чт, 24 марта 2016 г. в 20:01, mishoboss notifications@github.com:
